### ISSUE TITLE
2024.01.17 주간 위클리

### ISSUE THREAD

**Issue by her0807** [Nexters/Don-t-Forget---Server#15]
## 한 것 👍🏻
- [x] api 설계
- [x] git branch 전략 -> 명사로 작성, 그외 prefix 기본으로 사용
- [x] db 설계 ( erd 작성 완료)
- [x]  git commit history 청소

## todo 종하
- [x] DB 환경 구축

## todo 수진
- [x]  pr 머지 전략 설정
- [ ]  pr 템플릿 설정

### 공통으로 할 것 
- [x] 디비설계 고민해보기
- [ ]  Spring-batch 학습
- [ ] fcm push 학습
